### ISSUE TITLE
In-Game Test

### ISSUE THREAD

**Issue by snjlee58** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02#128]
In-Game 테스트 작성

**Comment by snjlee58** [comment]
[InGameTest.xlsx](https://github.com/user-attachments/files/18051216/InGameTest.xlsx)
<img width="877" alt="image" src="https://github.com/user-attachments/assets/b6961018-e161-4260-a536-a096ec4fdeba">

**Comment by snjlee58** [comment]
[InGameTest_Complete.xlsx](https://github.com/user-attachments/files/18093998/InGameTest_Complete.xlsx)

<img width="877" alt="image" src="https://github.com/user-attachments/assets/ad8f8980-f449-4116-bcf6-06ec593bfa2c">

**Comment by gyusang** [comment]
추가적인 QA 내용

1. (Hold) 게임 도중에 Go back / Restart 기능이 없음. 의도적으로 세 번 죽는 게 크게 어렵진 않으므로 없이 배포?
2. LevelClearScene이 전체화면에서 UI가 scaling되지 않고 애니메이션 재생되지 않음
3. 별 개수 기준이나 점수가 너무 후함.
4. (Hold) Level1 일부 장애물 보이지 않음 (잘못된 타일맵)
5. (GF3 Failure) `life = 1` 상태에서 카메라 밖으로 이동당할 때 Finish line을 넘기면 Clear됨.
