### ISSUE TITLE
(UE-024) Persistent Storage 테스팅

### ISSUE THREAD

**Issue by gyusang** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02#60]
Persistent Storage를 테스트하는 체크리스트 작성.

**Comment by gyusang** [comment]
[PersistentStorageTest.xlsx](https://github.com/user-attachments/files/17878173/PersistentStorageTest.xlsx)
<img width="1692" alt="image" src="https://github.com/user-attachments/assets/9bb12751-ea64-4544-ac1b-6d56e64a6e06">

**Comment by snjlee58** [comment]
[PersistentStorageTest_Complete.xlsx](https://github.com/user-attachments/files/17975011/PersistentStorageTest_Complete.xlsx)
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/8d519909-2dd6-4a78-a4a4-f8ef22e91495">

**Comment by snjlee58** [comment]
[PersistentStorageTest_Trial2_Complete.xlsx](https://github.com/user-attachments/files/17994564/PersistentStorageTest_Trial2_Complete.xlsx)
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/dbbc87fe-0b7a-4a15-9154-6d0f79100448">
