### ISSUE TITLE
(UE-021) 게임 클리어 테스트

### ISSUE THREAD

**Issue by gyusang** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02#72]
게임 클리어 테스트 작성

**Comment by gyusang** [comment]
<img width="1721" alt="image" src="https://github.com/user-attachments/assets/73e69570-8af7-4da2-87e6-03bbc59855c8">


[GameClearTest.xlsx](https://github.com/user-attachments/files/17930787/GameClearTest.xlsx)

**Comment by snjlee58** [comment]
[GameClearTest_Complete.xlsx](https://github.com/user-attachments/files/17975021/GameClearTest_Complete.xlsx)
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/476ff884-ef80-4f82-91b4-fdd6cacde769">
