### ISSUE TITLE
게임 실패 테스트

### ISSUE THREAD

**Issue by gyusang** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-02#73]
게임 실패 테스트 작성

**Comment by gyusang** [comment]
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/8a3f2af4-447f-4d5b-88b5-1f3077280bf5">
[GameFailTest.xlsx](https://github.com/user-attachments/files/17930895/GameFailTest.xlsx)

**Comment by snjlee58** [comment]
[GameFailTest_Complete.xlsx](https://github.com/user-attachments/files/17975034/GameFailTest_Complete.xlsx)
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/5dcc2b64-3ff8-4ce4-9766-0bfc4488daa0">

**Comment by snjlee58** [comment]
[GameFailTest_Trial2_Complete.xlsx](https://github.com/user-attachments/files/17994384/GameFailTest_Trial2_Complete.xlsx)
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/ef11209c-3203-4dc0-b16f-cd6fca7431b7">
